#! /bin/sh

die() {
  echo "$1"
  exit 1
}

source $APPDIR/AppRun.env
APP_TMP=/tmp/dosemu2apps/$APP_NAME
APP_TMPDIR=$APP_TMP/app
mkdir -p $APP_TMPDIR
DR_C=$APP_TMP/drive_c
mkdir -p $DR_C/tmp
APP_LOCALDIR=~/.local/state/dosemu2apps/$APP_NAME
mkdir -p $APP_LOCALDIR
FUSE_LOCALDIR=~/.fuse_overlayfs/dosemu2apps/$APP_NAME
mkdir -p $FUSE_LOCALDIR
fuse-overlayfs -o lowerdir=$APP_DIR -o upperdir=$APP_LOCALDIR \
  -o workdir=$FUSE_LOCALDIR $APP_TMPDIR || die "fuse-overlayfs failed"
dosemu -no-priv-sep --Flocal_dir $APP_TMP $APP_TMPDIR/$APP_EXE
fusermount -u $APP_TMPDIR
rm -rf $FUSE_LOCALDIR
